In [1]:
#En este notebook se mezclan los datos para generar las entradas de la red neuronal.
import numpy as np
import pickle

In [2]:
#carga los archivos dados los parámetros
def load_files(path,player,winner,index):
    with open(path+player+'_'+winner+'_'+str(index)+'.pkl', 'rb') as infile:
        data = np.array(pickle.load(infile),dtype=np.uint8)
    return data

In [3]:
# mezcla los datos estableciendo entradas donde gana las blancas o las negras, estas se ponen de manera aleatoria
# los valores de y corresponden a cual es beneficioso para las blancas, si es 1 corresponde a la entrada izquierda y si es 0 a la entrada derecha
# para las negras es la contraparte, si el resultado de y es 0 les beneficia la izquierda y 1 la derecha
def merge_data(white,black):
    size=white.shape[0]
    r = np.random.choice([True, False], size)
    x1_ = np.ones([size,1]).astype(int)
    x2_ = np.zeros([size,1]).astype(int)
    r=r.reshape(size,1)
    
    original_shape=list(white[0].shape)
    new_shape=np.concatenate(([size,1],original_shape)).astype(int)

    white=white.reshape([size,int(np.prod(original_shape))])
    black=black.reshape([size,int(np.prod(original_shape))])
    x1=np.where(r, white, black)
    x2=np.where(r, black, white)

    #para las blancas, 1 -> izquierda y 0-> derecha
    y=np.where(r, x1_, x2_)
    
    x1=x1.reshape(new_shape)
    x2=x2.reshape(new_shape)
    x = np.concatenate((x1,x2),axis=1)
    return x,y

In [ ]:
def all_random_permutation(lista):
    res=np.zeros([len(lista)*len(lista),2])
    i=0
    for val_i in lista:
        for val_j in lista:
            res[i]=[val_i, val_j]
            i+=1
    indices = np.random.permutation(res.shape[0])
    return res[indices].astype(int)

In [4]:
#desordena los índices
def shuffle_data(x,y):
    indices = np.random.permutation(y.shape[0])
    return x[indices],y[indices]
    

In [5]:
#Separa los datos en conjunto de entrenamiento y validación
def split_data(x,y,size_t=1/2):
    size_t=int(len(y)*size_t)
    x_train, x_test = x[:size_t,:], x[size_t:,:]
    y_train, y_test = y[:size_t,:], y[size_t:,:]
    return x_train,x_test,y_train,y_test

In [6]:
#Permine intercambiar los valores del dataset, es decir, si antes havia una tupla con [blanca, negra], ahora será [negra, blanca]
def flip_data(x,y):
    x=np.flip(x,axis=1)
    y=-y+1
    return x,y

In [7]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [8]:
x,y=merge_data(a,b)

In [9]:
x

array([[1, 4],
       [5, 2],
       [6, 3]])

In [10]:
y

array([[1],
       [0],
       [0]])

In [11]:
x,y=flip_data(x,y)

In [12]:
x

array([[4, 1],
       [2, 5],
       [3, 6]])

In [13]:
y

array([[0],
       [1],
       [1]])

In [14]:
b

array([4, 5, 6])

In [15]:
np.roll(b,1)

array([6, 4, 5])

In [ ]:
a=[1,2,3]
all_random_permutation(a)